// Privacy & Terms. Plain, honest, and accurate to how the app actually handles
// data (see the architecture: photos, identity, payments).
import React from "react";
import { useNavigate, useParams } from "react-router-dom";
import { Button } from "@callies-universe/core";
import { cfg } from "../subjects/index.js";

const DOCS = {
  privacy: {
    title: "Privacy & data",
    body: [
      "Your car photo is sent to our server only to identify the car (make/model), and only when a live backend is configured. We don't store it.",
      "We don't research or roast people — only the car. Comedy is aimed at the vehicle, never a person or group.",
      "Credits are tied to an anonymous device id by default — no account, no email — unless you choose to sign in.",
      "Payments are processed by Stripe; we never see or store card details.",
      "Roast text may be generated by an AI model (Anthropic) from the car's public reputation; with no backend it runs fully offline on a built-in set.",
    ],
  },
  terms: {
    title: "Terms",
    body: [
      "RoastMyRide is for entertainment. The roasts are jokes about a car, kept PG-13 — clever, never cruel.",
      "Don't upload photos of other people's cars without their consent. You're responsible for the photos you add.",
      "Credits are digital goods for generating + rendering reels; they're consumed when a roast is delivered.",
      "The service is provided as-is, without warranty. We may rate-limit or decline abusive use.",
      "Bring your own car. Leave your ego at the door.",
    ],
  },
};

export function Legal() {
  const go = useNavigate();
  const { doc } = useParams();
  const d = DOCS[doc] || DOCS.privacy;
  return (
    <div style={{ flex: 1, overflowY: "auto", padding: "var(--space-5)" }}>
      <h1 style={{ font: "var(--type-d2)", color: "var(--ink)", margin: "0 0 var(--space-3)" }}>{d.title}</h1>
      <div style={{ display: "flex", flexDirection: "column", gap: "var(--space-3)" }}>
        {d.body.map((p, i) => (
          <p key={i} style={{ font: "var(--type-body)", color: "var(--text-muted)", margin: 0 }}>{p}</p>
        ))}
      </div>
      <p style={{ font: "var(--type-legal)", color: "var(--text-hint)", marginTop: "var(--space-4)" }}>
        Questions? @{cfg("handle")}. {cfg("appName")} v0.3.0.
      </p>
      <div style={{ marginTop: "var(--space-4)" }}>
        <Button variant="secondary" onClick={() => go("/settings")}>Back to settings</Button>
      </div>
    </div>
  );
}
