// Subject config: the per-app parameterization layer.
// Every "Roast My ___" app is the same shell with a different config object.
// This file contains the CAR config (the reference subject). Other subjects live
// in siblings (texts.js, fit.js, room.js, profile.js).

export default {
  id: "car",
  appName: "RoastMyRide",
  handle: "roastmyride",
  // --- What the user uploads ---
  upload: {
    label: "Drop a pic of your ride",
    subcopy: "The more of your ride I can see, the harder they go.",
    cta: "Roast my car",
    alt: "Your car",
    replace: "Tap to replace",
    add: "Tap to add photo",
    addSub: "Camera or library",
    emoji: "📸",
    // The user CONFIRMS the exact car (required). Auto-ID pre-fills it as a guess,
    // but a wrong trim/year derails the whole roast, so we let the owner nail it.
    requireIdentity: true,
    identityLabel: "What is it?",
    identityPlaceholder: "e.g. 2015 Kia K900 V8",
    identityHint: "We guess from the photo. Fix anything we miss.",
    identityGuessing: "Taking a guess from your photo…",
    identityGuessed: "Our guess. Fix anything we got wrong:",
  },
  // --- Callie / mascot copy ---
  mascot: {
    home: "Add your car, pick two voices, and let them go.",
  },
  // --- AI behavior (displayed to user, not the raw prompt) ---
  brain: {
    safety: "The jokes are about the CAR, never the driver, owner, or any person. PG-13. Clever, never cruel.",
    subjectNoun: "your ride",
    researching: "ride",
  },
  // --- Context chip buckets (subject-specific) ---
  chips: {
    buckets: [
      {
        group: "Heat",
        items: [
          ["gentle", "😌 Gentle"],
          ["medium", "🌶 Medium"],
          ["brutal", "🔥 Brutal"],
        ],
      },
      {
        group: "Fair game",
        items: [
          ["thecar", "🚗 The car"],
          ["mytaste", "🎨 My taste"],
          ["themods", "🔧 The mods"],
          ["howidrive", "🏁 How I drive"],
          ["pricetag", "💸 Price tag"],
        ],
      },
      {
        group: "Vibe",
        items: [
          ["deadpan", "😐 Deadpan"],
          ["hype", "📣 Hype"],
          ["brainrot", "🧠 Brainrot"],
          ["battle", "🥊 Roast battle"],
        ],
      },
    ],
  },
  // --- UI theming ---
  theme: {
    emoji: "🚗",
    stickerTag: "🚗 the ride",
    accent: {
      "accent-700": "#9E2709",
      "accent-600": "#C7340F",
      "accent-500": "#E5481B",
      "accent-bright": "#FF6A1A",
      "accent-bright-2": "#FF8330",
      "accent-warm": "#FF9D4D",
      "accent-warm-2": "#FFB877",
      "accent-soft": "#FFF3E2",
    },
  },
  // --- Submission media display ---
  // Most submissions are phone photos in PORTRAIT. The scene frames them portrait;
  // cars sit wide in a tall frame, so we clip slightly (4:5, not full 3:4 / 9:16)
  // so the reveal isn't awkwardly long. objectFit: cover does the clipping.
  media: {
    aspect: "4 / 5",
  },
  // --- Monetization ---
  monetization: {
    creditLabel: "roasts",
    defaultCredits: 3,
  },
  // --- Progress steps while the roast is written + voiced ---
  cooking: {
    steps: (name) => [
      `${name} is looking up your ride…`,
      "Writing the roast…",
      "Sharpening the punchlines…",
      "Recording both voices…",
    ],
  },
  // --- Grade display ---
  grade: {
    edgeLabel: "on-the-car",
  },
  // --- Onboarding ---
  onboarding: {
    cta: "Roast my car 🔥",
  },
  // --- Celebrate ---
  celebrate: {
    cta: "Roast another car",
  },
  // --- Reveal ---
  reveal: {
    heading: "The full roast",
  },
  // --- Research field mapping ---
  research: {
    key: "car",
    labelFields: ["year", "make", "model"],
  },
  // --- Legal docs ---
  legal: {
    privacy: {
      title: "Privacy & data",
      body: [
        "Your car photo is sent to our server only to identify the car (make/model), and only when a live backend is configured. We don't store it.",
        "We don't research or roast people, only the car. Comedy is aimed at the vehicle, never a person or group.",
        "Credits are tied to an anonymous device id by default (no account, no email) unless you choose to sign in.",
        "Payments are processed by Stripe; we never see or store card details.",
        "Roast text may be generated by an AI model (Anthropic) from the car's public reputation; with no backend it runs fully offline on a built-in roast.",
      ],
    },
    terms: {
      title: "Terms",
      body: [
        "RoastMyRide is for entertainment. The roasts are jokes about a car, kept PG-13: clever, never cruel.",
        "Don't upload photos of other people's cars without their consent. You're responsible for the photos you add.",
        "Credits are digital goods for generating + rendering reels; they're consumed when a roast is delivered.",
        "The service is provided as-is, without warranty. We may rate-limit or decline abusive use.",
        "Bring your own car. Leave your ego at the door.",
      ],
    },
  },
  aso: {
    appName: "Roast My Ride",
    subtitle: "Your car. Roasted by two voices. In a video.",
    keywords: ["roast", "car", "funny", "AI comedy", "car roast", "roast my ride"],
  },
};
