// Subject config — Roast My Outfit / Fit Check.
// Every "Roast My ___" app is the same shell with a different config object.

export default {
  id: "outfit",
  appName: "RoastMyOutfit",
  handle: "roastmyoutfit",
  // --- What the user uploads ---
  upload: {
    label: "Drop a pic of your fit",
    subcopy: "The more I can see, the harder I cook.",
    cta: "Roast my fit",
    alt: "Your outfit",
    replace: "Tap to replace",
    add: "Tap to add photo",
    addSub: "Camera or library",
    emoji: "📸",
  },
  // --- Callie / mascot copy ---
  mascot: {
    home: "Callie's standing by. Drop a fit and watch it cook.",
  },
  // --- AI behavior (displayed to user, not the raw prompt) ---
  brain: {
    safety: "The jokes are about the OUTFIT and the CHOICES, never the person's body, looks, or worth. PG-13. Clever, never cruel.",
    subjectNoun: "your fit",
    researching: "fit",
  },
  // --- Context chip buckets (subject-specific) ---
  chips: {
    buckets: [
      {
        group: "Heat",
        items: [
          ["gentle", "😌 Gentle"],
          ["medium", "🌶 Medium"],
          ["brutal", "🔥 Brutal"],
        ],
      },
      {
        group: "Fair game",
        items: [
          ["thefit", "👕 The fit"],
          ["thecolors", "🎨 The colors"],
          ["theshoes", "👟 The shoes"],
          ["theaccessories", "💍 The accessories"],
          ["thevibe", "✨ The vibe"],
        ],
      },
      {
        group: "Vibe",
        items: [
          ["deadpan", "😐 Deadpan"],
          ["hype", "📣 Hype"],
          ["brainrot", "🧠 Brainrot"],
          ["battle", "🥊 Roast battle"],
        ],
      },
    ],
  },
  // --- UI theming ---
  theme: {
    emoji: "👕",
    stickerTag: "👕 the fit",
    accent: {
      "accent-700": "#8A1042",
      "accent-600": "#B8185E",
      "accent-500": "#E0247A",
      "accent-bright": "#FF4FA3",
      "accent-bright-2": "#FF73BC",
      "accent-warm": "#FF97D4",
      "accent-warm-2": "#FFBBE5",
      "accent-soft": "#FFE8F5",
    },
  },
  // --- Submission media display ---
  media: {
    aspect: "4 / 5",
  },
  // --- Monetization ---
  monetization: {
    creditLabel: "roasts",
    defaultCredits: 3,
  },
  // --- Cooking steps ---
  cooking: {
    steps: (name) => [
      `${name} is eyeing your fit…`,
      "Writing tonight's set…",
      "Working out the punchlines…",
      "Warming up the crowd…",
    ],
  },
  // --- Grade display ---
  grade: {
    edgeLabel: "on-the-fit",
  },
  // --- Onboarding ---
  onboarding: {
    cta: "Roast my fit 🔥",
  },
  // --- Celebrate ---
  celebrate: {
    cta: "Book another set",
  },
  // --- Reveal ---
  reveal: {
    heading: "The full set",
  },
  // --- Research field mapping ---
  research: {
    key: "outfit",
    labelFields: ["label"],
  },
  // --- Legal docs ---
  legal: {
    privacy: {
      title: "Privacy & data",
      body: [
        "Your photo is sent to our server only to analyze the outfit and styling choices, and only when a live backend is configured. We don't store it.",
        "We don't research or roast people — only the outfit and the choices. Comedy is aimed at the clothing and style, never a person's body, looks, or worth.",
        "Credits are tied to an anonymous device id by default — no account, no email — unless you choose to sign in.",
        "Payments are processed by Stripe; we never see or store card details.",
        "Roast text may be generated by an AI model (Anthropic) from the outfit description; with no backend it runs fully offline on a built-in set.",
      ],
    },
    terms: {
      title: "Terms",
      body: [
        "RoastMyOutfit is for entertainment. The roasts are jokes about outfits and styling choices, kept PG-13 — clever, never cruel.",
        "Don't upload photos of other people without their consent. You're responsible for the photos you add.",
        "Credits are digital goods for generating + rendering reels; they're consumed when a roast is delivered.",
        "The service is provided as-is, without warranty. We may rate-limit or decline abusive use.",
        "Bring your own fit. Leave your ego at the door.",
      ],
    },
  },
  // --- ASO metadata ---
  aso: {
    appName: "Roast My Outfit",
    subtitle: "Your fit. Roasted by a comedian. In a video.",
    keywords: ["roast", "outfit", "fit check", "fashion", "funny", "AI comedy", "style roast", "roast my outfit"],
  },
};
