// Subject config: Roast My Profile.
// Every "Roast My ___" app is the same shell with a different config object.

export default {
  id: "profile",
  appName: "RoastMyProfile",
  handle: "roastmyprofile",
  // --- What the user uploads ---
  upload: {
    label: "Drop a screenshot of your profile",
    subcopy: "The more I can see, the harder I cook.",
    cta: "Roast my profile",
    alt: "Your profile screenshot",
    replace: "Tap to replace",
    add: "Tap to add screenshot",
    addSub: "Camera or library",
    emoji: "📸",
  },
  // --- Callie / mascot copy ---
  mascot: {
    home: "Callie's standing by. Drop a profile and watch it cook.",
  },
  // --- AI behavior (displayed to user, not the raw prompt) ---
  brain: {
    safety: "The jokes are about the PROFILE CHOICES: bio, prompts, and photo composition. NEVER the person's looks, body, or worth. PG-13. Clever, never cruel.",
    subjectNoun: "your profile",
    researching: "profile",
  },
  // --- Context chip buckets (subject-specific) ---
  chips: {
    buckets: [
      {
        group: "Heat",
        items: [
          ["gentle", "😌 Gentle"],
          ["medium", "🌶 Medium"],
          ["brutal", "🔥 Brutal"],
        ],
      },
      {
        group: "Fair game",
        items: [
          ["thebio", "📝 The bio"],
          ["theprompts", "❓ The prompts"],
          ["thephotos", "📸 The photos"],
          ["thestrategy", "🎯 The strategy"],
          ["thevibe", "✨ The vibe"],
        ],
      },
      {
        group: "Vibe",
        items: [
          ["deadpan", "😐 Deadpan"],
          ["hype", "📣 Hype"],
          ["brainrot", "🧠 Brainrot"],
          ["battle", "🥊 Roast battle"],
        ],
      },
    ],
  },
  // --- UI theming ---
  theme: {
    emoji: "💘",
    stickerTag: "💘 the profile",
    accent: {
      "accent-700": "#7A4A0A",
      "accent-600": "#A0630E",
      "accent-500": "#C9801F",
      "accent-bright": "#E5A030",
      "accent-bright-2": "#F0B850",
      "accent-warm": "#F5D080",
      "accent-warm-2": "#FAE5B0",
      "accent-soft": "#FFF6E0",
    },
  },
  // --- Submission media display ---
  media: {
    aspect: "4 / 5",
  },
  // --- Monetization ---
  monetization: {
    creditLabel: "roasts",
    defaultCredits: 3,
  },
  // --- Cooking steps ---
  cooking: {
    steps: (name) => [
      `${name} is reading your profile…`,
      "Writing tonight's set…",
      "Working out the punchlines…",
      "Warming up the crowd…",
    ],
  },
  // --- Grade display ---
  grade: {
    edgeLabel: "in-the-profile",
  },
  // --- Onboarding ---
  onboarding: {
    cta: "Roast my profile 🔥",
  },
  // --- Celebrate ---
  celebrate: {
    cta: "Book another set",
  },
  // --- Reveal ---
  reveal: {
    heading: "The full set",
  },
  // --- Research field mapping ---
  research: {
    key: "profile",
    labelFields: ["label"],
  },
  // --- Legal docs ---
  legal: {
    privacy: {
      title: "Privacy & data",
      body: [
        "Your screenshot is sent to our server only to analyze the profile content (bio, prompts, photo choices), and only when a live backend is configured. We don't store it.",
        "We don't research or roast people, only the profile choices. Comedy is aimed at the bio, prompts, and photo composition, NEVER at a person's looks, body, or worth.",
        "Credits are tied to an anonymous device id by default (no account, no email) unless you choose to sign in.",
        "Payments are processed by Stripe; we never see or store card details.",
        "Roast text may be generated by an AI model (Anthropic) from the profile description; with no backend it runs fully offline on a built-in set.",
      ],
    },
    terms: {
      title: "Terms",
      body: [
        "RoastMyProfile is for entertainment. The roasts are jokes about profile choices (bio, prompts, photo composition), kept PG-13: clever, never cruel.",
        "Don't upload screenshots of other people's profiles without their consent. You're responsible for the screenshots you add.",
        "Credits are digital goods for generating + rendering reels; they're consumed when a roast is delivered.",
        "The service is provided as-is, without warranty. We may rate-limit or decline abusive use.",
        "Bring your own profile. Leave your ego at the door.",
      ],
    },
  },
  // --- ASO metadata ---
  aso: {
    appName: "Roast My Profile",
    subtitle: "Your profile. Roasted by a comedian. In a video.",
    keywords: ["roast", "profile", "dating", "bio", "funny", "AI comedy", "profile roast", "roast my profile"],
  },
};
