// Subject config — Roast My Room.
// Every "Roast My ___" app is the same shell with a different config object.

export default {
  id: "room",
  appName: "RoastMyRoom",
  handle: "roastmyroom",
  // --- What the user uploads ---
  upload: {
    label: "Drop a pic of your room",
    subcopy: "The more I can see, the harder I cook.",
    cta: "Roast my room",
    alt: "Your room",
    replace: "Tap to replace",
    add: "Tap to add photo",
    addSub: "Camera or library",
    emoji: "📸",
  },
  // --- Callie / mascot copy ---
  mascot: {
    home: "Callie's standing by. Drop a room and watch it cook.",
  },
  // --- AI behavior (displayed to user, not the raw prompt) ---
  brain: {
    safety: "The jokes are about the ROOM and the DECOR, never the person's worth or living situation. PG-13. Clever, never cruel.",
    subjectNoun: "your room",
    researching: "room",
  },
  // --- Context chip buckets (subject-specific) ---
  chips: {
    buckets: [
      {
        group: "Heat",
        items: [
          ["gentle", "😌 Gentle"],
          ["medium", "🌶 Medium"],
          ["brutal", "🔥 Brutal"],
        ],
      },
      {
        group: "Fair game",
        items: [
          ["thedecor", "🛋️ The decor"],
          ["thelayout", "📐 The layout"],
          ["thelighting", "💡 The lighting"],
          ["thefurniture", "🪑 The furniture"],
          ["thevibe", "✨ The vibe"],
        ],
      },
      {
        group: "Vibe",
        items: [
          ["deadpan", "😐 Deadpan"],
          ["hype", "📣 Hype"],
          ["brainrot", "🧠 Brainrot"],
          ["battle", "🥊 Roast battle"],
        ],
      },
    ],
  },
  // --- UI theming ---
  theme: {
    emoji: "🛋️",
    stickerTag: "🛋️ the room",
    accent: {
      "accent-700": "#2A4F3A",
      "accent-600": "#3B6B4F",
      "accent-500": "#4F8F6A",
      "accent-bright": "#68AD82",
      "accent-bright-2": "#88C9A0",
      "accent-warm": "#A6E0B8",
      "accent-warm-2": "#C8EFDA",
      "accent-soft": "#E8F9F0",
    },
  },
  // --- Submission media display ---
  media: {
    aspect: "4 / 5",
  },
  // --- Monetization ---
  monetization: {
    creditLabel: "roasts",
    defaultCredits: 3,
  },
  // --- Cooking steps ---
  cooking: {
    steps: (name) => [
      `${name} is scanning your room…`,
      "Writing tonight's set…",
      "Working out the punchlines…",
      "Warming up the crowd…",
    ],
  },
  // --- Grade display ---
  grade: {
    edgeLabel: "in-the-room",
  },
  // --- Onboarding ---
  onboarding: {
    cta: "Roast my room 🔥",
  },
  // --- Celebrate ---
  celebrate: {
    cta: "Book another set",
  },
  // --- Reveal ---
  reveal: {
    heading: "The full set",
  },
  // --- Research field mapping ---
  research: {
    key: "room",
    labelFields: ["label"],
  },
  // --- Legal docs ---
  legal: {
    privacy: {
      title: "Privacy & data",
      body: [
        "Your photo is sent to our server only to analyze the room decor and layout, and only when a live backend is configured. We don't store it.",
        "We don't research or roast people — only the room and the decor. Comedy is aimed at the space, never a person's worth or living situation.",
        "Credits are tied to an anonymous device id by default — no account, no email — unless you choose to sign in.",
        "Payments are processed by Stripe; we never see or store card details.",
        "Roast text may be generated by an AI model (Anthropic) from the room description; with no backend it runs fully offline on a built-in set.",
      ],
    },
    terms: {
      title: "Terms",
      body: [
        "RoastMyRoom is for entertainment. The roasts are jokes about room decor and layout, kept PG-13 — clever, never cruel.",
        "Don't upload photos of other people's spaces without their consent. You're responsible for the photos you add.",
        "Credits are digital goods for generating + rendering reels; they're consumed when a roast is delivered.",
        "The service is provided as-is, without warranty. We may rate-limit or decline abusive use.",
        "Bring your own room. Leave your ego at the door.",
      ],
    },
  },
  // --- ASO metadata ---
  aso: {
    appName: "Roast My Room",
    subtitle: "Your room. Roasted by a comedian. In a video.",
    keywords: ["roast", "room", "decor", "home", "funny", "AI comedy", "room roast", "roast my room"],
  },
};
