// Subject config — Roast My Texts.
// Every "Roast My ___" app is the same shell with a different config object.

export default {
  id: "texts",
  appName: "RoastMyTexts",
  handle: "roastmytexts",
  // --- What the user uploads ---
  upload: {
    label: "Drop a screenshot of your texts",
    subcopy: "The more context I can see, the harder I cook.",
    cta: "Roast my texts",
    alt: "Your text screenshot",
    replace: "Tap to replace",
    add: "Tap to add screenshot",
    addSub: "Camera or library",
    emoji: "📸",
  },
  // --- Callie / mascot copy ---
  mascot: {
    home: "Callie's standing by. Drop a text thread and watch it cook.",
  },
  // --- AI behavior (displayed to user, not the raw prompt) ---
  brain: {
    safety: "The jokes are about the TEXTS, never the people. PG-13. Clever, never cruel.",
    subjectNoun: "your texts",
    researching: "text thread",
  },
  // --- Context chip buckets (subject-specific) ---
  chips: {
    buckets: [
      {
        group: "Heat",
        items: [
          ["gentle", "😌 Gentle"],
          ["medium", "🌶 Medium"],
          ["brutal", "🔥 Brutal"],
        ],
      },
      {
        group: "Fair game",
        items: [
          ["thethread", "🧵 The thread"],
          ["myreplies", "🗣️ My replies"],
          ["greenbubbles", "🟢 Green bubbles"],
          ["readreceipts", "✅ Read receipts"],
          ["responsetime", "⏳ Response time"],
          ["emojigame", "😂 Emoji game"],
        ],
      },
      {
        group: "Vibe",
        items: [
          ["deadpan", "😐 Deadpan"],
          ["hype", "📣 Hype"],
          ["brainrot", "🧠 Brainrot"],
          ["battle", "🥊 Roast battle"],
        ],
      },
    ],
  },
  // --- UI theming ---
  theme: {
    emoji: "💬",
    stickerTag: "💬 the thread",
    accent: {
      "accent-700": "#2C4A70",
      "accent-600": "#3A5A8A",
      "accent-500": "#4E7BB8",
      "accent-bright": "#6A9ED8",
      "accent-bright-2": "#8AB8E0",
      "accent-warm": "#A8CEEA",
      "accent-warm-2": "#C8E0F0",
      "accent-soft": "#EBF5FB",
    },
  },
  // --- Monetization ---
  monetization: {
    creditLabel: "roasts",
    defaultCredits: 3,
  },
  // --- Cooking steps ---
  cooking: {
    steps: (name) => [
      `${name} is reading your texts…`,
      "Writing tonight's set…",
      "Working out the punchlines…",
      "Warming up the crowd…",
    ],
  },
  // --- Grade display ---
  grade: {
    edgeLabel: "in-the-texts",
  },
  // --- Onboarding ---
  onboarding: {
    body: "You bring the text thread, the app brings the roast — and I'll be right here losing it in the corner. Clever, never cruel.",
    cta: "Roast my texts 🔥",
  },
  // --- Celebrate ---
  celebrate: {
    cta: "Book another set",
  },
  // --- Reveal ---
  reveal: {
    heading: "The full set",
  },
  // --- Research field mapping ---
  research: {
    key: "texts",
    labelFields: ["label"],
  },
  // --- Legal docs ---
  legal: {
    privacy: {
      title: "Privacy & data",
      body: [
        "Your screenshot is sent to our server only to analyze the text conversation, and only when a live backend is configured. We don't store it.",
        "We don't research or roast people — only the text messages. Comedy is aimed at the conversation, never a person or group.",
        "Credits are tied to an anonymous device id by default — no account, no email — unless you choose to sign in.",
        "Payments are processed by Stripe; we never see or store card details.",
        "Roast text may be generated by an AI model (Anthropic) from the text conversation; with no backend it runs fully offline on a built-in set.",
      ],
    },
    terms: {
      title: "Terms",
      body: [
        "RoastMyTexts is for entertainment. The roasts are jokes about text messages, kept PG-13 — clever, never cruel.",
        "Don't upload screenshots of other people's conversations without their consent. You're responsible for the screenshots you add.",
        "Credits are digital goods for generating + rendering reels; they're consumed when a roast is delivered.",
        "The service is provided as-is, without warranty. We may rate-limit or decline abusive use.",
        "Bring your own texts. Leave your ego at the door.",
      ],
    },
  },
  // --- ASO metadata ---
  aso: {
    appName: "Roast My Texts",
    subtitle: "Your texts. Roasted by a comedian. In a video.",
    keywords: ["roast", "text", "text roast", "funny", "AI comedy", "screenshot", "messages", "roast my texts"],
  },
};
